### ISSUE TITLE
How often is docker image updated?

### ISSUE THREAD

**Issue by Toxicable** [buchgr/bazel-remote#202]
Hey team, we're looking at doing a deployment of this however we noticed that the docker image on DockerHub is a month old.
However there was a release on this repository 6 days ago and last commit was 8 hours ago.

**Comment by mostynb** [comment]
The short answer is "not very often, at the moment". @buchgr is trying to figure this out, but he's quite busy.

In the meantime, there are instructions in the README.md that describe how to build the docker image and install it in your local registry- would that work for you?

**Comment by Toxicable** [comment]
Ah I understand.
Until we can get that a little more automated having more regular releases that have the built artifacts, similar to what is here https://github.com/buchgr/bazel-remote/releases/tag/v1.0.0 will make it easier to make our own docker imges.
We'd prefer not have to get setup to build this repository.

**Comment by Toxicable** [comment]
For anyone elses reference we made this docker container
```
FROM ubuntu:18.04

WORKDIR /app

RUN apt-get update \
&& apt-get install -y --no-install-recommends software-properties-common curl

RUN VERSION=1.0.0 \
 && curl -L -o bazel-remote https://github.com/buchgr/bazel-remote/releases/download/v${VERSION}/bazel-remote-${VERSION}-linux-x86_64 \
 && chmod +x ./bazel-remote

EXPOSE 80
CMD ["./bazel-remote", "--port=80", "--config_file=/config"]
```
and execute it with docker-compose like
```
version: '2'

services:
  bazel-cache:
    image: muck.rl.team:8445/soa/bazel-cache:0.0.0
    volumes:
      - data:/data
      - ./config.yaml:/config
    restart: unless-stopped
    ports:
      - 80:8080

volumes:
  data:
```
and all your config sits in a config.yaml 
```
dir: /data
max_size: 1000
```
