### ISSUE TITLE
Doesn't work when run under Docker

### ISSUE THREAD

**Issue by marcus-sa** [buchgr/bazel-remote#206]
I keep hitting this error when trying to use this as a remote cache under Docker:
```
ERROR: Failed to query remote execution capabilities: UNAVAILABLE: io exception
```

I've built and pushed from the master branch onto my local docker registry and started it using 
```
docker run -v $DIR:/data -p 9090:8080 $IMAGE
```

**Comment by mostynb** [comment]
I think you need to add another -p arg for the gRPC API, which listens on a different port to the HTTP API. eg `-p 9092:9092` (bazel-remote's default port for gRPC is 9092).

**Comment by mostynb** [comment]
I have updated this section of the README.md.

I will close this issue now- please reopen if this does not work for you.

**Comment by marcus-sa** [comment]
@mostynb I don't know how I could've missed that, thanks!

**Comment by marcus-sa** [comment]
I can't get it to work with TLS tho.
This is my `docker-compose.yml` file, but I get the exact same error:
```
version: '3'
services:
  server:
    image: ''
    container_name: bazel-remote-cache
    restart: always
    environment:
      BAZEL_REMOTE_TLS_CERT_FILE: /etc/bazel-remote/server.crt
      BAZEL_REMOTE_TLS_KEY_FILE: /etc/bazel-remote/server.key
      BAZEL_REMOTE_GRPC_PORT: 9092
      BAZEL_REMOTE_HTPASSWD_FILE: /etc/bazel-remote/.htpasswd
      BAZEL_REMOTE_DIR: /data
      BAZEL_REMOTE_MAX_SIZE: 15
    ports:
      - 9092:9092
      - 8080:8080
    volumes:
      - server_data:/data
      - ./.htpasswd:/etc/bazel-remote/.htpasswd
      - ./server.key:/etc/bazel-remote/server.key
      - ./server.crt:/etc/bazel-remote/server.crt

volumes:
  server_data: {}
```

and this is the value I use:
```
build:remote-cache --remote_cache=grpcs://user:pass@0.0.0.0:9092
```
