### ISSUE TITLE
Remote API: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by UebelAndre** [buchgr/bazel-remote#304]
I'm running into the following error when I use `experimental_remote_asset_api`
```
server_1  | 2020/07/06 00:51:42 bazel-remote built with go1.14.3 from git commit 6abc54f50d40b0d5dcc3eb902d9cbd46e892215b.
server_1  | 2020/07/06 00:51:42 Initial RLIMIT_NOFILE cur: 1048576 max: 1048576
server_1  | 2020/07/06 00:51:42 Setting RLIMIT_NOFILE cur: 1048576 max: 1048576
server_1  | 2020/07/06 00:51:42 Migrating files (if any) to new directory structure: /data/ac
server_1  | 2020/07/06 00:51:42 Migrating files (if any) to new directory structure: /data/cas
server_1  | 2020/07/06 00:51:42 Loading existing files in /data.
server_1  | 2020/07/06 00:51:42 Sorting cache files by atime.
server_1  | 2020/07/06 00:51:42 Building LRU index.
server_1  | 2020/07/06 00:51:42 Finished loading disk cache files.
server_1  | 2020/07/06 00:51:42 Loaded 0 existing disk cache items.
server_1  | 2020/07/06 00:51:42 Starting HTTPS server on address :8080
server_1  | 2020/07/06 00:51:42 HTTP AC validation: enabled
server_1  | 2020/07/06 00:51:42 Starting gRPC server on address :9090
server_1  | 2020/07/06 00:51:42 gRPC AC dependency checks: enabled
server_1  | 2020/07/06 00:51:42 experimental gRPC remote asset API: enabled
server_1  | 2020/07/06 00:52:16 GRPC GETCAPABILITIES
server_1  | 2020/07/06 00:52:25 GRPC GETCAPABILITIES
server_1  | 2020/07/06 00:52:40 GRPC GETCAPABILITIES
server_1  | 2020/07/06 00:52:46 GRPC GETCAPABILITIES
server_1  | 2020/07/06 00:52:48 failed to get URI: https://static.rust-lang.org/dist/rust-1.44.1-x86_64-apple-darwin.tar.gz err: Get "https://static.rust-lang.org/dist/rust-1.44.1-x86_64-apple-darwin.tar.gz": x509: certificate signed by unknown authority
```

My `.bazelrc`
```
build --remote_cache=grpcs://bazelcache.local:9090
build --experimental_remote_downloader=grpcs://bazelcache.local:9090
build --keep_going
```

My bazel-remote config file
```
dir: /data
max_size: 256

port: 8080
grpc_port: 9090

tls_cert_file: /etc/ssl/cert.pem
tls_key_file:  /etc/ssl/key.pem

experimental_remote_asset_api: true
```

My docker-compose file.
```
---
services:
  server:
    environment:
      - BAZEL_REMOTE_CONFIG_FILE=/etc/bazel-remote/config.conf
    image: bazel/buchgr:bazel-remote
    ports:
      - 8080:8080/tcp
      - 9090:9090/tcp
    restart: unless-stopped
    volumes:
      - /home/user/data:/data:Z
      - /home/user/bazel-remote.conf:/etc/bazel-remote/config.conf:Z
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem:ro
      - /etc/ssl/key.pem:/etc/ssl/key.pem:ro

version: "2.4"
```

A repo that reproduces this issue.
[repro.zip](https://github.com/buchgr/bazel-remote/files/4876272/repro.zip)

I also want to note that I built a new image off of 6abc54f50d40b0d5dcc3eb902d9cbd46e892215b 

Is anyone else able to reproduce this with a similar (if not the same) setup?
