### ISSUE TITLE
Crash when reaching maximum disk size

### ISSUE THREAD

**Issue by priestjim** [buchgr/bazel-remote#481]
**`bazel-remote` version**: `1.3.3`

**Configuration**:
```yaml
"dir": "/var/cache/bazel-remote-cache"
"grpc_port": 9092
"max_size": 30
"port": 8080
"storage_mode": "zstd"
"http_read_timeout": "30s"
"http_write_timeout": "30s"
"enable_endpoint_metrics": true
"experimental_remote_asset_api": true
"s3_proxy":
  "bucket": "[redacted]"
  "endpoint": "s3.amazonaws.com"
  "disable_ssl": false
  "iam_role_endpoint": "http://169.254.169.254"
  "prefix": ""
  "region": "[redacted]"
```

**Deployment setup**: AWS EKS, Kubernetes 1.17, AMI `ami-06db2453ecb8dfbe6`, host directory mounted as a volume, image pulled directly from dockerhub (no customizations):
```yaml
        volumeMounts:
        - mountPath: /etc/config.yaml
          name: bazel-remote-cache-configmap
          readOnly: true
          subPath: config.yaml
        - mountPath: /var/cache/bazel-remote-cache
          name: bazel-remote-cache-data
[...]
      volumes:
      - emptyDir: {}
        name: bazel-remote-cache-data
      - configMap:
          name: bazel-remote-cache-configmap
          optional: false
        name: bazel-remote-cache-configmap`
```
Node volume is 100 GB, no other pods running.

**Issue**
`bazel-remote` operates nominally until it reaches its size limit and it has to purge LRU files. It then consistently crashes with:
```golang
goroutine 2043157 [runnable]:
syscall.Syscall(0x107, 0xffffffffffffff9c, 0xc00562a980, 0x0)
	src/syscall/asm_linux_amd64.s:20 +0x5
syscall.unlinkat(0x0, {0xc005d58f00, 0x0}, 0x0)
	GOROOT/src/syscall/zsyscall_linux_amd64.go:127 +0xd4
syscall.Unlink(...)
	GOROOT/src/syscall/syscall_linux.go:185
os.Remove.func1(...)
	GOROOT/src/os/file_unix.go:302
os.ignoringEINTR(...)
	GOROOT/src/os/file_posix.go:246
os.Remove({0xc005d58f00, 0x0})
	GOROOT/src/os/file_unix.go:301 +0x45
github.com/buchgr/bazel-remote/cache/disk.removeFile({0xc005d58f00, 0x78})
	cache/disk/disk.go:190 +0x25
created by github.com/buchgr/bazel-remote/cache/disk.New.func1
	cache/disk/disk.go:172 +0x205
```

The node has plenty of free disk space (~70 GB). This happens across instances, including freshly provisioned ones from ASG, so faulty memory/CPU/instance has been ruled out. Please advise.
