### ISSUE TITLE
Basic auth issue with gRPC

### ISSUE THREAD

**Issue by DamyrFr** [buchgr/bazel-remote#548]
Hi,

I have setup a Bazel remote instance, all is working as expected, except basic authentication with gRPC (it works with http and https).

When I use basic auth on remote with gRPC like this : `--remote_cache=grpcs://user:password@lb:9092`

Bazel gives me this error : 
```
INFO: Invocation ID: 9a76d3b6-4d7a-4a8a-aa34-f6d3c0b030e0
ERROR: Failed to query remote execution capabilities: UNAUTHENTICATED: no authentication metadata found
```
Anybody has an idea where this error may come from ?

**Setup :** 
* Bazel-remote on a compute instance behind a AWS ALB proxy

**Versions :** 
* Bazel-remote : 2.3.3
* Bazel client : 4.2.2

**Comment by mostynb** [comment]
Hmm, is the AWS ALB proxy trying to handle the authentication? BTW you should not try to load-balance across multiple bazel-remote instances, if a bazel client switches from one cache to another during a build it can fail. Maybe the simplest thing to do is try without the load balancer?

**Comment by DamyrFr** [comment]
I use mono instance, the ALB is only here for handle certificate and the endpoint to simplify the management. I don't have any rules on this on, it's only forwarding.

When I target directly the instance, I can't use gRPC due to http2 exception. I will check for debug this error.

**Comment by DamyrFr** [comment]
I managed to make it work (even with AWS ALB).

After hours of debug, I have created a new configuration file from zero. Put the same parameters in, but this time it's working with gRPCs :thinking: 

To be honest I don't really know what is the root cause (all parameters are the same).

Thanks for the help :) I close this issue.

**Comment by leszczynskimikolaj** [comment]
@mostynb I have the same issue as @DamyrFr but I'm not that lucky to have it auto-magically resolved. I have an ALB with a single service and service pod behind. The ALB is just forwarding the traffic to proper target group. From some reason I'm getting the same error.
```
WARNING: Failed to query remote execution capabilities: UNAUTHENTICATED: no authentication metadata found
```
or actually, it is a warning

**Comment by mostynb** [comment]
@leszczynskimikolaj: I don't have any experience with ALB unfortunately. I wonder if you could share a redacted version of the configuration- maybe something will jump out at us?

**Comment by leszczynskimikolaj** [comment]
@mostynb you mean remote cache config?

**Comment by mostynb** [comment]
I meant the ALB config. But your bazel-remote config might be useful too.

**Comment by leszczynskimikolaj** [comment]
Env vars that I set in my k8s bazel remote cache pod:
```
BAZEL_REMOTE_DIR=/home/nonroot/app/cache
BAZEL_REMOTE_MAX_SIZE=128
BAZEL_REMOTE_STORAGE_MODE=zstd
BAZEL_REMOTE_ZSTD_IMPLEMENTATION=go
BAZEL_REMOTE_GRPC_ADDRESS=0.0.0.0:9092
BAZEL_REMOTE_IDLE_TIMEOUT=0s
BAZEL_REMOTE_MAX_QUEUED_UPLOADS=1000000
BAZEL_REMOTE_NUM_UPLOADERS=100
BAZEL_REMOTE_S3_ENDPOINT=<redacted>
BAZEL_REMOTE_S3_BUCKET=<redacted>
BAZEL_REMOTE_S3_PREFIX=cache
BAZEL_REMOTE_S3_AUTH_METHOD=iam_role
BAZEL_REMOTE_S3_DISABLE_SSL=false
BAZEL_REMOTE_S3_UPDATE_TIMESTAMPS=false
BAZEL_REMOTE_S3_REGION=us-west-2
BAZEL_REMOTE_DISABLE_HTTP_AC_VALIDATION=false
BAZEL_REMOTE_DISABLE_GRPS_AC_DEPS_CHECK=false
BAZEL_REMOTE_ENABLE_AC_KEY_INSTANCE_MANGLING=false
BAZEL_REMOTE_ENABLE_ENDPOINT_METRICS=false
BAZEL_REMOTE_EXPERIMENTAL_REMOTE_ASSET_API=false
BAZEL_REMOTE_ACCESS_LOG_LEVEL=all
BAZEL_REMOTE_HTPASSWD_FILE=/etc/bazel-remote-cache/.htpasswd
BAZEL_REMOTE_TLS_CERT_FILE=/opt/certs/cert.pem
BAZEL_REMOTE_TLS_KEY_FILE=/opt/certs/key.pem
```

and the ALB:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brc-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 9092}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
```
