### ISSUE TITLE
Basic auth disabled for `/status` endpoint

### ISSUE THREAD

**Issue by bu3** [buchgr/bazel-remote#652]
Hi,

I'm having an issue deploying `bazel-remote` in a K8s cluster using `/status` as liveness probe with basic authentication enabled.
I cannot enable `allow_unauthenticated_reads` because of some internal security requirement but that means that `/status` returns 401 and K8s kills my deployment.

Is there any way to disable authentication for `/status` only?

**Comment by mostynb** [comment]
Have you considered using the `/grpc.health.v1.Health/Check` (gRPC) service for this?

**Comment by bu3** [comment]
No. Sorry I didn't. I don't get it though. You mean to use it for a liveness probe over gRPC?

Something like this?
```
  livenessProbe:
    grpc:
      port: 9092
      service: /grpc.health.v1.Health/Check
  readinessProbe:
    grpc:
      port: 9092
      service: /grpc.health.v1.Health/Check
```

**Comment by mostynb** [comment]
Yes. I don't have a great knowledge of kubernetes so I can't offer much help with that side of things, but maybe the discussion in #522 is helpful? This gRPC service is supposed to always be reachable (as long as you haven't disabled gRPC support in bazel-remote) regardless of authentication status.

**Comment by bu3** [comment]
That's great. Thanks for getting back so fast

**Comment by mostynb** [comment]
No problem. There's also a brief mention of this in the kubernetes notes section of the README.md - suggestions for how to improve that are weclome, if you have any.

**Comment by bu3** [comment]
Hi @mostynb,

just to help anyone else dealing with the same issue, this deployment works fine with k8s >= 1.24:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: bazel-remote-cache
        image: buchgr/bazel-remote-cache:latest
        ports:
          - containerPort: 7442
            name: http
            protocol: TCP
          - containerPort: 15372
            name: http-scone-mgmt
            protocol: TCP
          - containerPort: 8080
            name: http-default
            protocol: TCP
        livenessProbe:
            grpc:
              service: /grpc.health.v1.Health/Check
              port: 9092
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
        readinessProbe:
            grpc:
              service: /grpc.health.v1.Health/Check
              port: 9092
            failureThreshold: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 10
```
