### ISSUE TITLE
Automatically rotate logs

### ISSUE THREAD

**Issue by ob** [buchgr/bazel-remote#88]
Right now {{bazel-remote}} just logs to stdout/stderr, which means it needs to be spawn by redirecting those to a file and the log files managed externally.

Alternatively, it could use something like [lumberjack|https://github.com/natefinch/lumberjack] and rotate the logs itself automatically. It would need some new configuration parameters to determine log location (the default would be under the cache directory), and how often to rotate the logs.

I propose the following new config options:

```yaml
log_path: path.log        # optional, if relative path it goes under cacheDir, defaults to bazel-remote.log
log_max_size:   500  # in megabytes
log_max_backups:  3  # number of backup files to keep around
log_max_age:     28  # how many days to keep the around for
log_compress:  true  # disabled by default
```
